attach_duration_msec: null
attach_pid: null
config_dir: /opt/rocm-7.2.2/libexec/rocprofiler-compute/rocprof_compute_soc/analysis_configs
device: 0
dispatch: null
filter_blocks:
- 2.1.16
- 2.1.17
- 16.1.2
- 17.1.0
format_rocprof_output: csv
hip_trace: false
join_type: grid
kernel: null
kernel_names: false
kokkos_trace: false
list_available_metrics: false
list_blocks: null
list_metrics: null
list_sets: false
loglevel: 20
mem_level: ALL
mode: profile
name: mla_moe_current_mem
no_roof: true
path: /remote/vast0/thangdo/mla-moe/rocprof_compute_current_mem
pc_sampling_interval: 1048576
pc_sampling_method: stochastic
quiet: false
remaining: ./run /remote/vast0/share-mv/deepseek-ai/DeepSeek-V2-Lite getp /tmp/mla-moe-rocprof-requests.txt
  /tmp/mla-moe-current-profile-mem.out 2
retain_rocpd_output: false
rocprofiler_sdk_library_path: /opt/rocm/lib/librocprofiler-sdk.so
roof_only: false
roofline_data_type:
- FP32
set_selected: mem_thruput
sort: kernels
spatial_multiplexing: null
specs: false
subpath: gpu_model
target: null
verbose: 0
